UI/WebStore/Components/BrandsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using WebStore.Domain.ViewModels;
using WebStore.Interfaces.Services;
using WebStore.Services.Mapping;

namespace WebStore.Components
{
    public class BrandsViewComponent : ViewComponent
    {
        private readonly IProductData _ProductData;

        public BrandsViewComponent(IProductData ProductData) => _ProductData = ProductData;

        public IViewComponentResult Invoke(string BrandId)
        {
            ViewBag.BrandId = int.TryParse(BrandId, out var id) ? id : (int?) null;
            return View(GetBrands());
        }

        private IEnumerable<BrandsViewModel> GetBrands() =>
            _ProductData.GetBrands()
            .OrderBy(brand => brand.Order)
            .Select(brand => new BrandsViewModel
            {
                Id = brand.Id,
                Name = brand.Name,
                ProductsCount = _ProductData.GetProducts(new Domain.ProductFilter { BrandId = brand.Id }).Products.Count()
            });
    }
}

UI/WebStore/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Collections.Generic;
using System.Linq;
using WebStore.Domain;
using WebStore.Domain.ViewModels;
using WebStore.Interfaces.Services;
using WebStore.Services.Mapping;

namespace WebStore.Controllers
{
    public class CatalogController : Controller
    {
        private const string __CatalogPageSize = "CatalogPageSize";

        private readonly IProductData _ProductData;
        private readonly IConfiguration _Configuration;

        public CatalogController(IProductData ProductData, IConfiguration Configuration)
        {
            _ProductData = ProductData;
            _Configuration = Configuration;
        }

        public IActionResult Index(int? BrandId, int? SectionId, int Page = 1, int? PageSize = null)
        {
            var page_size = PageSize
                ?? (int.TryParse(_Configuration[__CatalogPageSize], out var value ) ? value : null);

            var Filter = new ProductFilter
            {
                BrandId = BrandId,
                SectionId = SectionId,
                Page = Page,
                PageSize = page_size,
            };

            var(products, total_count) = _ProductData.GetProducts(Filter);

            return View(new CatalogViewModel
            {
                SectionId = SectionId,
                BrandId = BrandId,
                Products = products.OrderBy(p => p.Order).FromDTO().ToView(),
                PageViewModel = new PageViewModel
                {
                    Page = Page,
                    PageSize = page_size ?? 0,
                    TotalItems = total_count
                }
            });
        }

        public IActionResult Details(int id)
        {
            var product = _ProductData.GetProductById(id);
            return View(product.FromDTO().ToView());
        }

        #region WebAPI

        public IActionResult GetFeaturesItems(int? BrandId, int? SectionId, int Page = 1, int? PageSize = null) => 
            PartialView("Partial/_FeaturesItems", GetProducts(BrandId, SectionId, Page, PageSize));

        private IEnumerable<ProductViewModel> GetProducts(int? BrandId, int? SectionId, int Page, int? PageSize) =>
            _ProductData.GetProducts(new ProductFilter
            {
                SectionId = SectionId,
                BrandId = BrandId,
                Page = Page,
                PageSize = PageSize ?? (int.TryParse(_Configuration[__CatalogPageSize], out var size ) ? size : null)
            })
            .Products.OrderBy(p => p.Order)
            .FromDTO()
            .ToView();

        #endregion
    }
}

UI/WebStore/Controllers/EmployeesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using AutoMapper;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using WebStore.Domain.Identity;
using WebStore.Domain.Models;
using WebStore.Interfaces.Services;
using WebStore.Domain.ViewModels;

namespace WebStore.Controllers
{
    [Authorize]
    public class EmployeesController : Controller
    { 
        private readonly IEmployeesData _Employees;

        // Создание конфигурации сопоставления и настройка AutoMapper'а для Employee in EmployeeViewModel
        private readonly Mapper mapperViewModel = new Mapper(new MapperConfiguration(cfg => cfg.CreateMap<Employee, EmployeeViewModel>()));

        // Создание конфигурации сопоставления и настройка AutoMapper'а для EmployeeViewModel in Employee
        private readonly Mapper omapperModel = new Mapper(new MapperConfiguration(cfg => cfg.CreateMap<EmployeeViewModel, Employee>()));

        public EmployeesController(IEmployeesData EmloyeesData) => _Employees = EmloyeesData;

        public IActionResult Index()
        {
            return View(mapperViewModel.Map<IEnumerable<EmployeeViewModel>>(_Employees.Get()));
        }

        public IActionResult Details(int id)
        {
            var employee = _Employees.Details(id);
            if (employee is null)
                return NotFound();
            return View(mapperViewModel.Map<EmployeeViewModel>(employee));
        }

        public IActionResult Create(Employee employee) => View("Edit", new EmployeeViewModel());

        #region Edit
        [Authorize (Roles = Role.Administrators)]
        public IActionResult Edit(int id)
        {
            if (id <= 0) return BadRequest();
            var employee = _Employees.Details(id);
            if (employee is not null)
                return View(mapperViewModel.Map<EmployeeViewModel>(employee));
            return NotFound();
        }

        [HttpPost]
        public IActionResult Edit(EmployeeViewModel model)
        {
            if (model is null)
                throw new ArgumentNullException(nameof(model));

            if (!ModelState.IsValid) return View(model);

            var employee = omapperModel.Map<Employee>(model);

            if (employee.Id == 0)
                _Employees.Create(employee);
            else
                _Employees.Edit(employee);

            return RedirectToAction("Index");
        }
        #endregion

        #region Delete
        [Authorize(Roles = Role.Administrators)]
        public IActionResult Delete(int id)
        {
            if (id <= 0) return BadRequest();

            var employee = _Employees.Details(id);

            if (employee is null)
                return NotFound();

            return View(mapperViewModel.Map<EmployeeViewModel>(employee));
        }

        [HttpPost]
        public IActionResult DeleteConfirmed(int id)
        {
            _Employees.Delete(id);
            return RedirectToAction("Index");
        }
        #endregion
    }
}

UI/WebStore/Controllers/WebAPIController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebStore.Interfaces.TestAPI;

namespace WebStore.Controllers
{
    public class WebAPIController : Controller
    {
        private readonly IValuesService _ValuesService;

        public WebAPIController(IValuesService ValuesService) => _ValuesService = ValuesService;

        public IActionResult Index()
        {
            var values = _ValuesService.Get();
            return View(values);
        }
    }
}

UI/WebStore/Views/Shared/Partial/_CategoryTabNavigation.cshtml
<ul class="nav nav-tabs">
    <li class="active"><a href="#tshirt" data-toggle="tab">T-Shirt</a></li>
    <li><a href="#blazers" data-toggle="tab">Blazers</a></li>
    <li><a href="#sunglass" data-toggle="tab">Sunglass</a></li>
    <li><a href="#kids" data-toggle="tab">Kids</a></li>
    <li><a href="#poloshirt" data-toggle="tab">Polo shirt</a></li>
</ul>

UI/WebStore/Views/Shared/Partial/_CategoryTabPanel.cshtml
<div class="tab-pane fade" id="blazers">
    <div class="col-sm-3">
        <partial name="Partial/_ProductImageWrapperWithOutOverlay" />
    </div>
    <div class="col-sm-3">
        <partial name="Partial/_ProductImageWrapperWithOutOverlay" />
    </div>
    <div class="col-sm-3">
        <partial name="Partial/_ProductImageWrapperWithOutOverlay" />
    </div>
    <div class="col-sm-3">
        <partial name="Partial/_ProductImageWrapperWithOutOverlay" />
    </div>
</div>

UI/WebStore/Views/Shared/Partial/_CategoryTabPanelActive.cshtml
<div class="tab-pane fade active in" id="tshirt">
    <div class="col-sm-3">
        <partial name="Partial/_ProductImageWrapperWithOutOverlay" />
    </div>
    <div class="col-sm-3">
        <partial name="Partial/_ProductImageWrapperWithOutOverlay" />
    </div>
    <div class="col-sm-3">
        <partial name="Partial/_ProductImageWrapperWithOutOverlay" />
    </div>
    <div class="col-sm-3">
        <partial name="Partial/_ProductImageWrapperWithOutOverlay" />
    </div>
</div>

UI/WebStore/Views/Shared/Partial/_FeaturesItems.cshtml
@model IEnumerable<ProductViewModel>

<div class="features_items">
    <!--features_items-->
    <h2 class="title text-center">Товары</h2>

    @if (Model is null)
    {
        <p>По вашему запросу ничего не найдено</p>
    }
    else
    {
        @foreach (var product in Model)
        {
            <div class="col-sm-4">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/shop/@product.ImageUrl" alt="@product.Name" />
                            <h2>@product.Price.ToString("c")</h2>
                            <p><a asp-controller="Catalog" 
                                  asp-action="Details" 
                                  asp-route-id="@product.Id"
                                  asp-route-SectionId="@Context.Request.Query["SectionId"]" 
                                  asp-route-BbrandId="@Context.Request.Query["BrandId"]">
                                @product.Name</a></p>
                            <a asp-controller="Cart"
                               asp-action="Add"
                               asp-route-id="@product.Id" 
                               data-id="@product.Id"
                               class="btn btn-default add-to-cart">
                               <i class="fa fa-shopping-cart"></i>В корзину
                            </a>
                        </div>
                        <div class="product-overlay">
                            <div class="overlay-content">
                                <h2>@product.Price.ToString("c")</h2>
                                <p><a asp-controller="Catalog" 
                                      asp-action="Details" 
                                      asp-route-id="@product.Id" 
                                      asp-route-SectionId="@Context.Request.Query["SectionId"]" 
                                      asp-route-BbrandId="@Context.Request.Query["BrandId"]">
                                    @product.Name</a></p>
                                <a asp-controller="Cart"
                                   asp-action="Add"
                                   asp-route-id="@product.Id" 
                                   data-id="@product.Id"
                                   class="btn btn-default add-to-cart">
                                   <i class="fa fa-shopping-cart"></i>В корзину
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="choose">
                        <ul class="nav nav-pills nav-justified">
                            <li><a href="#"><i class="fa fa-plus-square"></i>В избранное</a></li>
                            <li><a href="#"><i class="fa fa-plus-square"></i>В сравнение</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        }
    }

    <!-- Костыль -->
    @*@{
        if (ViewBag.Title == "Shop")
        {
            <ul class="pagination">
                <li class="active"><a href="">1</a></li>
                <li><a href="">2</a></li>
                <li><a href="">3</a></li>
                <li><a href="">&raquo;</a></li>
            </ul>
        }

    }*@
    </div><!--features_items-->

UI/WebStore/Views/Shared/Partial/_Footer.cshtml
<footer id="footer">
    <!--Footer-->
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="companyinfo">
                        <h2><span>e</span>-shopper</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
                    </div>
                </div>
                <div class="col-sm-7">
                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe1.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe2.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe3.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe4.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="address">
                        <img src="~/images/home/map.png" alt="" />
                        <p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-widget">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Service</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Online Help</a></li>
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">Order Status</a></li>
                            <li><a href="#">Change Location</a></li>
                            <li><a href="#">FAQ’s</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Quock Shop</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">T-Shirt</a></li>
                            <li><a href="#">Mens</a></li>
                            <li><a href="#">Womens</a></li>
                            <li><a href="#">Gift Cards</a></li>
                            <li><a href="#">Shoes</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Policies</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Terms of Use</a></li>
                            <li><a href="#">Privecy Policy</a></li>
                            <li><a href="#">Refund Policy</a></li>
                            <li><a href="#">Billing System</a></li>
                            <li><a href="#">Ticket System</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>About Shopper</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Company Information</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="#">Store Location</a></li>
                            <li><a href="#">Affillate Program</a></li>
                            <li><a href="#">Copyright</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3 col-sm-offset-1">
                    <div class="single-widget">
                        <h2>About Shopper</h2>
                        <form action="#" class="searchform">
                            <input type="text" placeholder="Your email address" />
                            <button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
                            <p>Get the most recent updates from <br />our site and be updated your self...</p>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
                <p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
            </div>
        </div>
    </div>

</footer><!--/Footer-->

UI/WebStore/Views/Shared/Partial/_Header.cshtml
<header id="header">
    <!--header-->
    <div class="header_top">
        <!--header_top-->
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="contactinfo">
                        <ul class="nav nav-pills">
                            <li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="social-icons pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header_top-->

    <div class="header-middle">
        <!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="logo pull-left">
                        <a href="index.html"><img src="~/images/home/logo.png" alt="" /></a>
                    </div>
                    <div class="btn-group pull-right">
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                USA
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Canada</a></li>
                                <li><a href="#">UK</a></li>
                            </ul>
                        </div>

                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                DOLLAR
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Canadian Dollar</a></li>
                                <li><a href="#">Pound</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                       <vc:user-info />
                </div>
            </div>
        </div>
    </div><!--/header-middle-->

    <div class="header-bottom">
        <!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">

                        <partial name="Partial/_MainMenu" />

                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="search_box pull-right">
                        <input type="text" placeholder="Search" />
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->

UI/WebStore/Views/Shared/Partial/_LeftSideBar.cshtml
<div class="left-sidebar">
    @*@Component.InvokeAsync("Sections")*@
    <vc:sections section-id="@Context.Request.Query["SectionId"]"/>

    <vc:brands brand-id="@Context.Request.Query["BrandId"]"/>

    <div class="price-range">
        <!--price-range-->
        <h2>Price Range</h2>
        <div class="well text-center">
            <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2"><br />
            <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
        </div>
    </div><!--/price-range-->

    <div class="shipping text-center">
        <!--shipping-->
        <img src="~/images/home/shipping.jpg" alt="" />
    </div><!--/shipping-->

</div>

UI/WebStore/Views/Shared/Partial/_MainMenu.cshtml
<ul class="nav navbar-nav collapse navbar-collapse">
    <li><a is-active-route asp-controller="Home" asp-action="Index">Главная</a></li>
    <li class="dropdown">
        <a href="#">Магазин<i class="fa fa-angle-down"></i></a>
        <ul role="menu" class="sub-menu">
            <li><a is-active-route ignore-action asp-controller="Catalog" asp-action="Index">Каталог</a></li>
            <li><a is-active-route asp-controller="Home" asp-action="CheckOut">Checkout</a></li>
            <li><a is-active-route asp-controller="Home" asp-action="Cart">Cart</a></li>
            <li><a is-active-route asp-controller="Home" asp-action="Login">Login</a></li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#">Blog<i class="fa fa-angle-down"></i></a>
        <ul role="menu" class="sub-menu">
            <li><a is-active-route asp-controller="Home" asp-action="Blog">Blog List</a></li>
            <li><a is-active-route asp-controller="Home" asp-action="BlogSingle">Blog Single</a></li>
        </ul>
    </li>
    <li><a is-active-route asp-controller="Home" asp-action="Error404">404</a></li>
    <li><a is-active-route asp-controller="Home" asp-action="ContactUs">Contact</a></li>
    <li><a is-active-route asp-controller="Employees" asp-action="Index">Сотрудники</a></li>
    <li><a asp-controller="WebAPI" asp-action="Index" class="@IsActive("WebAPI")">WebAPI</a></li>
</ul>

@functions {
    string IsActive(string Controller, string Action = "Index") =>
        Equals(Controller, ViewContext.RouteData.Values["Controller"])
        && Equals(Action, ViewContext.RouteData.Values["Action"])
        ? "active"
        : null;
}

UI/WebStore/Views/Shared/Partial/_ProductImageWrapperWithOutOverlay.cshtml
<div class="product-image-wrapper">
    <div class="single-products">
        <div class="productinfo text-center">
            <img src="~/images/home/gallery1.jpg" alt="" />
            <h2>$56</h2>
            <p>Easy Polo Black Edition</p>
            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
        </div>
    </div>
</div>

UI/WebStore/Views/Shared/Partial/_RecommendedItem.cshtml
<div class="item">
    <div class="col-sm-4">
        <partial name="Partial/_ProductImageWrapperWithOutOverlay" />
    </div>
    <div class="col-sm-4">
        <partial name="Partial/_ProductImageWrapperWithOutOverlay" />
    </div>
    <div class="col-sm-4">
        <partial name="Partial/_ProductImageWrapperWithOutOverlay" />
    </div>
</div>

UI/WebStore/Views/Shared/Partial/_RecommendedItemActive.cshtml
<div class="item active">
    <div class="col-sm-4">
        <partial name="Partial/_ProductImageWrapperWithOutOverlay" />
    </div>
    <div class="col-sm-4">
        <partial name="Partial/_ProductImageWrapperWithOutOverlay" />
    </div>
    <div class="col-sm-4">
        <partial name="Partial/_ProductImageWrapperWithOutOverlay" />
    </div>
</div>

UI/WebStore/Views/Shared/Partial/_RecommendedItems.cshtml
<div class="recommended_items">
    <!--recommended_items-->
    <h2 class="title text-center">recommended items</h2>

    <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">

            <partial name="Partial/_RecommendedItemActive" />

            <partial name="Partial/_RecommendedItem" />

        </div>
        <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
            <i class="fa fa-angle-left"></i>
        </a>
        <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
            <i class="fa fa-angle-right"></i>
        </a>
    </div>
</div><!--/recommended_items-->

UI/WebStore/Views/Shared/Partial/_Scripts.cshtml
<script src="~/js/jquery.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/jquery.scrollUp.min.js"></script>
<script src="~/js/jquery.prettyPhoto.js"></script>

<environment include="Development">
    <script src="~/js/price-range.js"></script>
    <script src="~/js/main.js" asp-append-version="true"></script>
</environment>

<environment exclude="Development">
    <script src="~/js/scripts.js" asp-append-version="true"></script>
</environment>

<script src="~/js/Cart/CartLogic.js" asp-append-version="true"></script>

<script>
    $(function () {
        Cart.init({
            getCartViewLink: "@Url.Action("GetCartView","Cart")",
            addToCartLink: "@Url.Action("AddAPI","Cart")",
            decrementLink: "@Url.Action("DecrementAPI","Cart")",
            removeFromCartLink: "@Url.Action("RemoveAPI","Cart")"
        });
    })
</script>

UI/WebStore/Views/Shared/Partial/_Styles.cshtml
<link href="~/css/bootstrap.min.css" rel="stylesheet">
<link href="~/css/font-awesome.min.css" rel="stylesheet">
<link href="~/css/prettyPhoto.css" rel="stylesheet">

<!--[if lt IE 9]>
<script src="js/html5shiv.js"></script>
<script src="js/respond.min.js"></script>
<![endif]-->
<environment include="Development">
    <link href="~/css/main.css" rel="stylesheet" asp-append-version="true">
    <link href="~/css/animate.css" rel="stylesheet">
    <link href="~/css/responsive.css" rel="stylesheet">
    <link href="~/css/price-range.css" rel="stylesheet">
</environment>

<environment exclude="Development">
    <link href="~/css/styles.css" rel="stylesheet" asp-append-version="true">
</environment>

@* asp-append-version="true" - для обновления файла принудительно (к названию дописывается хэш-сумма *@